Update app.js
Save Mongoose data models inside var. This is another attempt at getting
the app to work on Heroku.
App deployed to Heroku but crashes. It works locally, (ex. with "heroku
local" command).
Trying to find a solution since commit
03d70704840825a7588f124d7fe51ef2e020e875.
Heroku logs show: "Error: Cannot find module './models/Posts'"
Also shows ENOENT error of dotenv not finding a .env file to open on
Heroku. However, that shouldn't crash app, since environmental variables
have been set as config vars on Heroku.